name: Download M3U/M3U8 Files # Changed name to reflect M3U8 handling

on:
  workflow_dispatch: # Allows you to trigger the workflow manually from the GitHub UI
  schedule:
    - cron: '5,35 * * * *' # Runs every hour at :05 and :35 minutes past the hour UTC

permissions:
  contents: write # Grant write permissions to the GITHUB_TOKEN

jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # The default GITHUB_TOKEN has sufficient permissions for pushing to the same repository,
        # provided the 'contents: write' permission is granted at the workflow level.

      - name: Download M3U/M3U8 Files # Changed step name
        run: |
          # Exit script on any error and treat pipe failures as errors
          set -eo pipefail

          URL_FILE="m3u_urls.txt" # Define the source file for URLs

          if [[ ! -f "$URL_FILE" ]]; then
            echo "Error: URL file '$URL_FILE' not found."
            exit 1
          fi

          echo "Reading URLs from $URL_FILE..."
          while IFS= read -r url || [[ -n "$url" ]]; do
            # Skip empty lines and lines starting with # (comments)
            if [[ -z "$url" ]] || [[ "$url" == \#* ]]; then
              continue
            fi

            # Extract filename from URL and remove query parameters for a cleaner name
            filename_with_query=$(basename "$url")
            filename="${filename_with_query%%\?*}" # Removes everything after '?'

            if [[ -z "$filename" ]]; then
              echo "Warning: Could not determine a valid filename for URL: $url. Skipping."
              continue
            fi

            echo "Downloading $filename from $url..."
            # -sS: Silent mode, but still show errors
            # -L: Follow redirects
            # --fail: Exit with an error code on HTTP server errors (4xx, 5xx)
            # --connect-timeout 10: Timeout for connection phase
            # --max-time 30: Maximum time for the whole operation
            # --output: Downloads the file directly to the current directory
            curl -sS -L --fail --connect-timeout 10 --max-time 30 \
              --output "$filename" "$url"
          done < "$URL_FILE"

          echo "All M3U/M3U8 files processed." # Changed message

      - name: Commit and push downloaded M3U/M3U8 files to M3u branch root # Changed step name
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update M3U/M3U8 files" # Changed commit message
          # Updated file_pattern to look for both .m3u and .m3u8 files directly in the root
          file_pattern: "*.m3u *.m3u8"
          # The default GITHUB_TOKEN is used here.
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          # push_options: '--force' # Uncomment if you need to force push (use with caution)
